version: '3.8'

services:
  ai-codereview:
    build: .
    ports:
      - "7001:7001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/"]
      interval: 30s
      timeout: 10s
      retries: 3